spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon_db
    username: postgres
    password: 1556
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: hackathon
testing:
  app:
    secret: SBJHPYEQUWGRVXCNVJELQTHUDVCMMSGUYQEBWRELVEGWQEARWLAKHWUYGYHREKWQPJJYAPNHYHNGQAMG